// progress-bar-react/src/components/progressBar.tsx
const ProgressBar = (props: ProgressBarProps) => {
    const {color, value, maxValue} = props;

    return (
        <div style={{width: '100%', height: '5px', position: 'fixed'}}>
            <div style={{
                width: Math.trunc((value / maxValue) * 100) + "%",
                height: '100%',
                backgroundColor: color,
                transition: 'width 200ms ease-in-out'
            }}/>
        </div>
    )
}

type ProgressBarProps = {
    color: string,
    value: number,
    maxValue: number,
}

export default ProgressBar;

// progress-bar-vue/src/components/ProgressBar.vue
<template>
  <div :style="{
        position: 'fixed',
        width: '100%',
        height: '5px',
      }">
    <div :style="{
        height: '5px',
        width: Math.trunc(this.value / this.maxValue * 100) + '%',
        backgroundColor: this.color,
        transition: 'width 200ms ease-in-out'
      }">
    </div>
  </div>
</template>

<script>
export default {
  name: "ProgressBar",
  props: {
    color: String,
    value: Number,
    maxValue: Number
  },
}
</script>
