// progress-bar-angular/src/app/app.component.ts
import {AfterViewInit, Component, OnDestroy, ViewChild} from '@angular/core';
import {ProgressBarComponent} from './components/progress-bar.component';
import {fromEvent, Subscription} from 'rxjs';

@Component({
  selector: 'app-root',
  template: `
    <app-progress-bar color="white"></app-progress-bar>
    <app-block color="red"></app-block>
    <app-block color="green"></app-block>
    <app-block color="blue"></app-block>
  `
})
export class AppComponent implements AfterViewInit, OnDestroy {
  @ViewChild(ProgressBarComponent) pb: ProgressBarComponent;

  subscription: Subscription;

  ngAfterViewInit(): void {
    this.pb.maxValue = document.body.scrollHeight - document.documentElement.clientHeight;

    const handleScroll = () => {
      this.pb.value = window.pageYOffset;
    };

    fromEvent(document, 'scroll').subscribe(handleScroll);
  }

  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }
}

// progress-bar-vue/src/App.vue
<template>
  <div id="app">
    <ProgressBar color="white" :value="current" :max-value="max"/>
    <Block color="red"></Block>
    <Block color="green"></Block>
    <Block color="blue"></Block>
  </div>
</template>

<script>
import Block from "@/components/Block";
import ProgressBar from "@/components/ProgressBar";

export default {
  name: 'App',
  components: {
    ProgressBar,
    Block
  },
  data() {
    return {
      current: 0,
      max: 0
    }
  },
  mounted() {
    this.max = document.body.scrollHeight - document.documentElement.clientHeight;
    window.addEventListener('scroll', this.handleScroll);
  },
  destroyed() {
    window.removeEventListener('scroll', this.handleScroll);
  },
  methods: {
    handleScroll() {
      this.current = window.pageYOffset;
    }
  }
}
</script>

<style>
body {
  margin: 0;
}
</style>
